baseURL = 'https://hades595.github.io/'
languageCode = 'en-us'
title = 'thesimpleDFIRblog'
theme = "paper"

builddrafts = true

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light

  # header social icons
  avatar = 'cpanda595@gmail.com'                 # gravatar email or image url
  github = 'hades595'                 # github.com/YOUR_GITHUB_ID

  # home page profile
  name = 'Chirag Mehta'
  bio = 'Student. Constantly Learning.'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon